CREATE TABLE IF NOT EXISTS cardiac_exams (
    id CHAR(36) PRIMARY KEY,
    encounter_id CHAR(36) NOT NULL UNIQUE,
    cough BOOLEAN NOT NULL DEFAULT FALSE,
    syncope BOOLEAN NOT NULL DEFAULT FALSE,
    exercise_intolerance BOOLEAN NOT NULL DEFAULT FALSE,
    nocturnal_tachypnea BOOLEAN NOT NULL DEFAULT FALSE,
    body_weight_kg DECIMAL(7,2) NULL,
    heart_rate_bpm SMALLINT UNSIGNED NULL,
    respiratory_rate_rpm SMALLINT UNSIGNED NULL,
    systolic_bp_mmhg SMALLINT UNSIGNED NULL,
    murmur_grade VARCHAR(16) NULL,
    rhythm VARCHAR(80) NULL,
    vhs DECIMAL(6,2) NULL,
    vlas DECIMAL(6,2) NULL,
    home_rr_rpm SMALLINT UNSIGNED NULL,
    la_ao DECIMAL(6,3) NULL,
    lvidd_cm DECIMAL(6,3) NULL,
    lviddn DECIMAL(6,3) NULL,
    lvids_cm DECIMAL(6,3) NULL,
    fs_percent DECIMAL(6,2) NULL,
    e_velocity_ms DECIMAL(6,3) NULL,
    a_velocity_ms DECIMAL(6,3) NULL,
    e_a_ratio DECIMAL(6,3) NULL,
    tr_vmax_ms DECIMAL(6,3) NULL,
    pr_vmax_ms DECIMAL(6,3) NULL,
    mr_severity VARCHAR(20) NULL,
    sam BOOLEAN NOT NULL DEFAULT FALSE,
    lvoto BOOLEAN NOT NULL DEFAULT FALSE,
    sec_present BOOLEAN NOT NULL DEFAULT FALSE,
    la_thrombus BOOLEAN NOT NULL DEFAULT FALSE,
    pericardial_effusion BOOLEAN NOT NULL DEFAULT FALSE,
    findings MEDIUMTEXT NULL,
    assessment MEDIUMTEXT NULL,
    acvim_stage VARCHAR(20) NULL,
    ph_risk VARCHAR(20) NULL,
    chf_status VARCHAR(20) NULL,
    follow_up_months SMALLINT UNSIGNED NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    CONSTRAINT fk_cardiac_exam_encounter
        FOREIGN KEY (encounter_id) REFERENCES encounters(id) ON DELETE CASCADE,
    INDEX idx_cardiac_exam_updated (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
